import React from 'react'
import { Sparkles, ShieldCheck, Clock, Shield, Users } from 'lucide-react'

export const TelemetryObservations = () => {
  return (
    <section className="bg-surface-card border border-border-main rounded-2xl p-6 space-y-5 transition-colors duration-200">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <Sparkles className="w-4 h-4 text-blue-400" />
          <h2 className="text-base font-semibold text-content-main">
            Developer Insights &amp; Telemetry Observations
          </h2>
        </div>
        <span className="px-2.5 py-1 text-[11px] font-semibold text-content-muted bg-surface-card-subtle border border-border-main rounded-md">
          Generated by DevIntel AI
        </span>
      </div>

      {/* 2x2 Grid of Observation Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* 1. Documentation Coverage */}
        <div className="bg-surface-card-inner border border-border-main rounded-xl p-4 flex items-start gap-3.5 hover:border-border-light transition-colors">
          <div className="w-8 h-8 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 mt-0.5">
            <ShieldCheck className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-content-main">
              Exceptional documentation coverage
            </h3>
            <p className="text-[11px] text-content-secondary leading-relaxed">
              Across 96% of public repositories, featuring interactive API
              references and comprehensive architecture diagrams.
            </p>
          </div>
        </div>

        {/* 2. Consistent Commit Velocity */}
        <div className="bg-surface-card-inner border border-border-main rounded-xl p-4 flex items-start gap-3.5 hover:border-border-light transition-colors">
          <div className="w-8 h-8 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 mt-0.5">
            <Clock className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-content-main">
              Consistent commit velocity
            </h3>
            <p className="text-[11px] text-content-secondary leading-relaxed">
              Peak productivity hours observed between 14:00 - 18:00 UTC with
              concentrated focus on Tuesdays and Thursdays.
            </p>
          </div>
        </div>

        {/* 3. High Dependency Freshness */}
        <div className="bg-surface-card-inner border border-border-main rounded-xl p-4 flex items-start gap-3.5 hover:border-border-light transition-colors">
          <div className="w-8 h-8 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 mt-0.5">
            <Shield className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-content-main">
              High dependency freshness
            </h3>
            <p className="text-[11px] text-content-secondary leading-relaxed">
              Automated Dependabot integration ensures 98% of dependency updates
              are merged within 48 hours of release.
            </p>
          </div>
        </div>

        {/* 4. Strong Open Source Collaboration */}
        <div className="bg-surface-card-inner border border-border-main rounded-xl p-4 flex items-start gap-3.5 hover:border-border-light transition-colors">
          <div className="w-8 h-8 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 mt-0.5">
            <Users className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-content-main">
              Strong open source collaboration
            </h3>
            <p className="text-[11px] text-content-secondary leading-relaxed">
              Maintains an average PR merge turnaround time of under 14 hours
              with robust external contributor engagement.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

export default TelemetryObservations
